spring:
  application:
    name: api-gateway

server:
  port: 9999

zuul:
  routes:
    server-one:
      path: /server-one/**
      serviceId: hello-service
    feign-consumer:
      path: /feign-consumer/**
      serviceId: feign-consumer


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    healthcheck:
      enabled: true
