server:
  port: 5000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahongbql/springcloud/
          search-paths: config
          username: mahongbql
          password: *********

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    enabled: true
    healthcheck:
      enabled: true


